# Generated by Django 3.2.9 on 2023-01-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221230_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codregister',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
